### PR TITLE
Bumped version to 1.3.3

### PR DESCRIPTION
**Pull request by JUANDIEGOGARITA**

### CODE REVIEW

**Comment by JUANDIEGOGARITA** [comment]
@rtrusona do you mean it should be 1.4.0 for the release that is happening right now? or for the next one?

**Comment by rtrusona** [comment]
For the release that is happening now.

**Comment by JUANDIEGOGARITA** [comment]
@rtrusona ok so I should bump the version to 1.4.0, create a tag for it and release it.
then, bump the version to 1.4.1 for the next iteration, am I right?

**Comment by rtrusona** [comment]
Yes sir 👍

**Pull request closed without merging**
